account/urls.py
"""
Account Routes used for authentication
"""
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    # /auth/login
    path('login/', views.login, name='login'),
    # /auth/signup
    path('singup/', views.signup, name='singup'),
    # /auth/logout
    path('logout/', views.logout, name='logout'),
]

student/urls.py
"""
Student Routes
"""
from django.urls import path
from . import views

app_name = 'student'

urlpatterns = [
    # /
    path('', views.list_student, name='list_student'),
    # /create
    path('create/', views.create_student, name='create_student'),
    # /edit/1
    path('edit/<int:student_id>/', views.edit_student, name='edit_student'),
    # /view/1
    path('view/<int:student_id>/', views.view_student, name='view_student'),
    # /delete/1
    path('delete/<int:student_id>/', views.delete_student, name='delete_student'),
]

student_curd/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('student.urls', namespace='student')),
    path('auth/', include('account.urls', namespace='account')),
]

student/models.py
"""
Student Models
"""
from django.db import models
from django.contrib.auth.models import AbstractUser

SCHOOL_TYPE = (
    ('ES', 'Elementry School'),
    ('MS', 'Middle School'),
    ('HS', 'High School')
)
GENDER_TYPE = (
    ('M', 'Male'),
    ('F', 'Female'),
)

class CustomUser(AbstractUser):
    """
    Custom User Model
    Adding extra fields age to the django's auth model
    """
    # Overrides the django's user model email field and made it unique
    # to replace USERNAME_FIELD as email.
    # This is done bcoz we don't want to use username field in the site
    email = models.EmailField(max_length=254, unique=True, db_index=True)
    name = models.CharField(max_length=100, default='')
    age = models.PositiveIntegerField(default=0)
    # We are going to show this gender field as a radio button. For this we set the
    # value for the 'default' argument and 'blank=False' so that django doesn't
    # include the blank choice '-----' in the from
    # Ref: https://stackoverflow.com/questions/42390311/remove-blank-from-radioselect/42401631#42401631
    gender = models.CharField(
        max_length=1,
        choices=GENDER_TYPE,
        default=GENDER_TYPE[0][0],
        blank=False
    )
    school = models.CharField(
        max_length=2,
        choices=SCHOOL_TYPE,
        null=True,
        blank=True
    )
    is_active = models.BooleanField(default=True)

    # Overriding username field and setting it as a none unique field bcoz
    # we don't want to use usernam in the site instead we want to use email for that
    username = models.CharField(max_length=40, unique=False, default='')
    # Setting email field as replacement to username field
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name', 'age', 'gender', 'school', 'is_active']

    def __str__(self):
        return self.email

student/forms.py
"""
Student Form Models
"""
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from .models import CustomUser, GENDER_TYPE, SCHOOL_TYPE
from django.forms import ModelForm, ValidationError

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = UserCreationForm.Meta.fields

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = UserChangeForm.Meta.fields

class UserForm(ModelForm):
    class Meta:
        model = CustomUser
        # Since we are using Django's User model, we only need to show the fields that are
        # needed for our use
        fields = ['name', 'age', 'email', 'gender', 'school', 'is_active']
        # To customize form field attributes
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter Name'
            }),
            'age': forms.NumberInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter Age'
            }),
            'gender': forms.RadioSelect(
                attrs={'class': 'form-check-input'},
                choices=GENDER_TYPE
            ),
            'email': forms.EmailInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter Email'
            }),
            'school': forms.Select(
                attrs={'class':'form-control', 'required': True},
                choices=SCHOOL_TYPE,
            ),
            'is_active': forms.CheckboxInput(
                attrs={'class':'form-check-input'},
            ),
        }
        # To show help text in form fields
        help_texts = {
            'name': 'Please enter your full name',
            'is_active': 'Untick this checkbox to disable the student',
        }

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        # Overriding default choice value '-----' to a string
        # Ref: https://stackoverflow.com/questions/12984013/how-to-change-empty-label-for-modelform-choice-field/14032358#14032358
        self.fields["school"].choices = [("", "Please choose a school"),]\
        + list(self.fields["school"].choices)[1:]

    def clean(self):
        # Gets the cleaned data
        cd = super(UserForm, self).clean()

        # To raise non field error
        # raise ValidationError('Non Field Test error')

        # Age Validation
        if cd['age'] < 5:
            raise ValidationError({
                'age': ValidationError(
                    "Age is invalid, Student must be least 5 year old or greater"
                )
            })
        return self.cleaned_data

student/views.py
"""
Student View Page
"""
from django.shortcuts import render, redirect
from django.db import connection
from django.contrib import messages
from util.db import to_dict

from .models import CustomUser
from .forms import UserForm, GENDER_TYPE, SCHOOL_TYPE

def list_student(request):
    """
    To List Students
    """
    students = CustomUser.objects.all()

    return render(request, 'student/list.html', {
        'students': students
    })

def create_student(request):
    """
    To Create New Student
    """
    # Initialized form model, if form is submitted then
    # the form data is automatically assigned from POST body
    form = UserForm(request.POST or None)
    # Process form on POST request
    if request.method == 'POST':
        # Validates the form
        if form.is_valid():
            # Saves the user data
            form.save()
            # Adding flash message
            messages.add_message(
                request,
                messages.SUCCESS,
                'Student data added successfully'
            )
            # Redirecting user to listing page
            return redirect('student:list_student')
        else:
            # Adding bootstrap error class to the invalid fields
            for error_field in form.errors:
                if error_field in form.fields:
                    form.fields[error_field].widget.attrs['class'] += ' is-invalid'
    # Renders the form
    return render(request, 'student/create.html', {'form': form})

def edit_student(request, student_id):
    """
    To Update Student
    """
    try:
        # Gets student model
        student = CustomUser.objects.get(pk=student_id)
        # Sets form data with student details
        form = UserForm(request.POST or None, instance=student)
    except CustomUser.DoesNotExist: # If( user not found
        # Redirect user to listing page with flash message
        messages.add_message(
            request,
            messages.ERROR,
            'Student not found!'
        )
        # Redirecting user back to student listing
        return redirect('student:list_student')
    else:
        if request.method == 'POST' and form.is_valid():
            form.save()
            # Setting success flash message
            messages.add_message(
                request,
                messages.SUCCESS,
                'Student data updated successfully'
            )
            # Redirecting user back to student listing
            return redirect('student:list_student')
        else:
            # Adding bootstrap error class to the invalid fields
            for error_field in form.errors:
                if error_field in form.fields:
                    form.fields[error_field].widget.attrs['class'] += ' is-invalid'

        # Renders the edit form
        return render(request, 'student/update.html', {'form':form})

def view_student(request, student_id):
    """
    To View Student Detail
    """
    # Executing raw sql queries
    sql = '''
        SELECT
            `id`,
            `name`,
            `age`,
            `email`,
            `gender`,
            `school`,
            `is_active`
        FROM
            `student_customuser`
        WHERE
            `id` = %s
        '''
    cursor = connection.cursor()
    # Binding params, so that django will filter its value to prevent sql injection
    cursor.execute(sql, [student_id])
    # Executing query
    result = cursor.fetchone()
    # Converting query results into dictionary containing column name as keys
    user_data = to_dict(cursor, result)
    # Rending template
    return render(request, 'student/view.html', {
        'user_data': user_data,
        'gender_data': dict(GENDER_TYPE),
        'school_data': dict(SCHOOL_TYPE)
    })

def delete_student(request, student_id):
    """
    To Delete Student
    """
    try:
        # Deletes user data
        CustomUser.objects.get(pk=student_id).delete()
        # Sets flash mesage
        messages.add_message(
            request,
            messages.INFO,
            'Student data deleted successfully'
        )
    except CustomUser.DoesNotExist: # If user not found
        # Sets flash mesage
        messages.add_message(
            request,
            messages.ERROR,
            'Student not found!'
        )
    # Redirect user to student listing page
    return redirect('student:list_student')

student/templates/student/create.html
{% extends "base.html" %}

{% block title %}Create Student{% endblock title %}

{% block content %}
<div class="col-md-6 offset-md-3 mt-3">
    <div class="card">
        <div class="card-title text-center mt-3">
            <span class="h4">Create Student</span>
        </div>
        <div class="card-body">
            {% include "student/student_form.html" %}
        </div>
    </div>
</div>
{% endblock content %}

student/templates/student/list.html
{% extends "base.html" %}
{% block content %}
<div class="col-md-6 offset-md-3 mt-3">
    <div class="col-md-2">
        <a href="{% url 'student:create_student' %}" class="btn btn-primary">Create Student</a>
    </div>
</div>
<div class="col-md-6 offset-md-2 mt-3">
    <table class="table table-dark">
        <thead>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col">Age</th>
            <th scope="col" class="text-center">Action</th>
        </thead>
        <tbody>
        {% for student in students %}
        <tr>
            <td scope="row">{{ student.name }}</td>
            <td>{{ student.email }}</td>
            <td>{{ student.age}}</td>
            <td class="text-center">
                <a href="{% url 'student:view_student' student.id %}" class="btn btn-success">View</a>
                <a href="{% url 'student:edit_student' student.id %}" class="btn btn-info">Edit</a>
                <a href="{% url 'student:delete_student' student.id %}" class="btn btn-danger student-delete">Delete</a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

</div>
{% endblock content %}
{% block script %}
<script>
    $('.student-delete').click(function(e){
        if (!confirm('Are you sure about deleting this student?')) {
            e.preventDefault()
        }
    })
</script>
{% endblock script %}

student/templates/student/student_form.html
{% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{form.non_field_errors}}
    </div>
{% endif %}

<form method="post" action=".">
    {% csrf_token %}
    <div class="form-group row">
        <label class="col-sm-2" for="{{form.name.id_for_label}}">Name</label>
        <div class="col-sm-10">
            {{form.name}}
            {% if form.name.help_text %}
                <small class="form-text text-muted">{{form.name.help_text|safe}}</small>
            {% endif %}

            {% if 'name' in form.errors %}
                <div class="invalid-feedback">
                {% for error in form.name.errors %}
                    <p>{{error}}</p>
                {% endfor %}
                </div>
            {% endif %}
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-2" for="{{form.age.id_for_label}}">Age</label>
        <div class="col-sm-10">
            {{form.age}}
            {% if form.age.help_text %}
                <small class="form-text text-muted">{{form.age.help_text|safe}}</small>
            {% endif %}

            {% if form.age.errors %}
                <div class="invalid-feedback">
                {% for error in form.age.errors %}
                    <p>{{error}}</p>
                {% endfor %}
                </div>
            {% endif %}
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-2">Gender</div>
        <div class="col-sm-10">
            {% for gender in form.gender %}
                <div class="form-check form-check-inline">
                    {{ gender.tag }}
                    <label class="form-check-label" for="{{ gender.id_for_label }}">{{ gender.choice_label }}</label>
                </div>
            {% endfor %}
            {% if form.gender.help_text %}
                <small class="form-text text-muted">{{form.gender.help_text|safe}}</small>
            {% endif %}

            {% if form.gender.errors %}
                <div class="invalid-feedback">
                {% for error in form.gender.errors %}
                    <p>{{error}}</p>
                {% endfor %}
                </div>
            {% endif %}
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-2" for="{{form.email.id_for_label}}">Email</label>
        <div class="col-sm-10">
            {{form.email}}
            {% if form.email.help_text %}
                <small class="form-text text-muted">{{form.email.help_text|safe}}</small>
            {% endif %}

            {% if form.email.errors %}
                <div class="invalid-feedback">
                {% for error in form.email.errors %}
                    <p>{{error}}</p>
                {% endfor %}
                </div>
            {% endif %}
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-2">School</div>
        <div class="col-sm-10">
            {{form.school}}
            {% if form.school.help_text %}
                <small class="form-text text-muted">{{form.school.help_text|safe}}</small>
            {% endif %}

            {% if form.school.errors %}
                <div class="invalid-feedback">
                {% for error in form.school.errors %}
                    <p>{{error}}</p>
                {% endfor %}
                </div>
            {% endif %}
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-2">Is Active</div>
        <div class="col-sm-10">
            <div class="form-check">
                {{ form.is_active }}
                {% if form.is_active.help_text %}
                    <small class="form-text text-muted">{{form.is_active.help_text|safe}}</small>
                {% endif %}
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-success col-sm-4 offset-sm-4">Submit</button>
</form>

student/templates/student/update.html
{% extends "base.html" %}

{% block title %}Edit Student{% endblock title %}

{% block content %}
<div class="col-md-6 offset-md-3 mt-3">
    <div class="card">
        <div class="card-title text-center mt-3">
            <span class="h4">Create Student</span>
        </div>
        <div class="card-body">
            {% include "student/student_form.html" %}
        </div>
    </div>
</div>
{% endblock content %}

student/templates/student/view.html
{% extends "base.html" %}
{% load template_helper %}

{% block title %}Student Detail{% endblock title %}

{% block content %}
<div class="col-md-6 offset-md-3 mt-3">
    <div class="card">
        <div class="card-title text-center mt-3">
            <span class="h4">Student Details</span>
        </div>
        <div class="card-body">
            <div class="col-md-6 offset-md-3">
                <table class="table table-striped">
                    <tr>
                        <th>ID</th>
                        <td>{{user_data.id}}</td>
                    </tr>
                    <tr>
                        <th>Name</th>
                        <td>{{user_data.name}}</td>
                    </tr>
                    <tr>
                        <th>Age</th>
                        <td>{{user_data.age}}</td>
                    </tr>
                    <tr>
                        <th>Gender</th>
                        <td>{{gender_data|get_dict_item:user_data.gender}}</td>
                    </tr>
                    <tr>
                        <th>Email</th>
                        <td>{{user_data.email}}</td>
                    </tr>
                    <tr>
                        <th>School</th>
                        <td>{{school_data|get_dict_item:user_data.school}}</td>
                    </tr>
                    <tr>
                        <th>Status</th>
                        <td>{% if user_data.is_active %}Active{% else %}Not Active{% endif %}</td>
                    </tr>
                </table>
            </div>
            <div class="col">
                <a class="btn btn-info" href="{% url 'student:list_student'%}">Go Back</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}